// LOCALHOST
###
GET http://localhost:8080/contacts

###
GET http://localhost:8080/contacts/678996ed004410fee44434c1


// Render.com

###
GET https://cse341-web-services-vw.onrender.com/

###
GET https://cse341-web-services-vw.onrender.com/johnclark

###
GET https://cse341-web-services-vw.onrender.com/contacts


###
GET https://cse341-web-services-vw.onrender.com/contacts/678996ed004410fee44434c1